apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ./ocirepository.yaml
  - ./ocirepository-postgres.yaml
  - ./ocirepository-redis.yaml
  - ./helmrelease-postgres.yaml
  - ./helmrelease-redis.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./httproute-external.yaml
