---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: obsidian-couchdb-secret
  data:
    - secretKey: COUCHDB_USER
      remoteRef:
        key: secret/obsidian-couchdb
        property: COUCHDB_USER
    - secretKey: COUCHDB_PASSWORD
      remoteRef:
        key: secret/obsidian-couchdb
        property: COUCHDB_PASSWORD
