---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: grafana-admin-password-secret
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: secret/grafana
        property: GF_SECURITY_ADMIN_PASSWORD
