---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-tracker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: speedtest-tracker-secret
  data:
    - secretKey: APP_USER
      remoteRef:
        key: secret/speedtest-tracker
        property: APP_USER
    - secretKey: APP_PASSWORD
      remoteRef:
        key: secret/speedtest-tracker
        property: APP_PASSWORD
