# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker-secret
  namespace: default
type: Opaque
stringData:
  APP_USER: ENC[AES256_GCM,data:cLUsPIliXoiDc9TzuxbbHEUbow==,iv:v6DcvvzTHGhujFuUSQeRn0BHfdyB56XFGNqnlqQL/Y4=,tag:wWAQyJWL+7tvqMEU7SnTJg==,type:str]
  APP_PASSWORD: ENC[AES256_GCM,data:0flLggEBrImsyfeSm+iD8BA=,iv:OoIyvzOfbtDdmCFSRZDRJQb2x4wOA6Me0l2aWPomXyo=,tag:Uus5c0sYunK/Km1DY03jSQ==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUXdGOThrSytoOXovK3R3
        NmF5K3RUWmdYcFA5c1dXTXZiYzA1WWwrT2pNCjRYUzNRODB0dFd4OGd1dUFERWU0
        Q1lwYjM5aWVGRDZyb0lIZGYzSkF2VlkKLS0tIFV4VFZtUFVXbXp2U2VsaDZBc2dW
        VUdYU0lIQzNYZG0ybGd4SzFCd2JXL00KzGefyuC8230Ss3zgKLiGFNPwp7pa3wQ3
        YD5xbO8Sr5l1BbsR8qGrXe1Pl7RmogOnBCU/6C6MbvKCSz7VTZofBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T16:59:08Z"
  mac: ENC[AES256_GCM,data:Qs7vWxZ79OwtBMLBpRVHbgPMgQZ4/i1q8Syd+A32PAq2UExT7pFTMI4PZSZQGryKN6TOPJNUKW/3sEN/lhRKVvB1VdVPUvsL7+zqkEMC4THULrCHStEdTr+WhoO9cbLc7dljLQiuuEQYoMJsfYR/35f41yLOon2MU7XRIkbNmNo=,iv:vfABb+ynLrvS3RuYCyOtzg5Fl+dg/1CffK+qQIYFbVI=,tag:Ix1NMLSbJyhUX/C2JMzGUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
