apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-secret
spec:
  interval: 1h
  path: ./kubernetes/apps/default/authentik/authentik/secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  dependsOn:
    - name: external-secrets-cluster-secret-store
      namespace: external-secrets
