# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
  namespace: default
type: Opaque
stringData:
  HOMEPAGE_VAR_SYNOLOGY_URL: ENC[AES256_GCM,data:fH9fyK6eby9F5mgVKj5YTbmLYUCH9g==,iv:V3RdF94DuBwdmDcaMKGS+LwRGQyphR5pTV8U/G4BlU0=,tag:M96/XWHMksgQLVXRzefc+A==,type:str]
  HOMEPAGE_VAR_SYNOLOGY_USERNAME: ENC[AES256_GCM,data:Mz2GL9nwFLzDxgk=,iv:+lVaN1nSUqxfu/EsRSVr/A4w4tbuow/tuClzJUTQXG8=,tag:Qkc2j2gpAQb/LPEaLebwjw==,type:str]
  HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:bGd7SCjKNtmfj1f/iNt8s7nImg==,iv:3nzi+BE52MAU1ZEIvQ4/zLzoVZIPCwMKXzZV5SJHJAY=,tag:bRb+pfUsomgIMjhVgZmFBQ==,type:str]
  HOMEPAGE_VAR_SPEEDTEST_URL: ENC[AES256_GCM,data:0I3xf6NOKQwhNQol20ZnPUWlCJ4uPUQfQuYrQIgTLVDe2x802L4bNfxAgQUzRuEjXWg=,iv:oJSmfNazkpH7LQyMeYmLRemeQxDsXJg6m6lPlY9gtOM=,tag:8mKqiknXGXGXVQhwT8ZyIg==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYWpkZVZiOEZjMjZKM0NN
        MFAvMXZMZXBYWmo3a0MrQXZRUDB2L3hSdjNNCmFpSFJ1Mk5TM3E5OGJDQU91MFUz
        ZlNaWFh5enh4cXFtelk2ZkI4VE45amcKLS0tIEVqZEpSUUJYZTROQU43SlpHeHMv
        TElCZm42d3F6SzR6R004bGhCSUVxMncKUDxUc/LRgX9HipZaDXkwrv0rOmA1qcgN
        s8cs6n22U7YfFCw/tzM29xUKhH9eP2JGlaHNu3OnfxQZlLXTjhC+Uw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:03:31Z"
  mac: ENC[AES256_GCM,data:WloWZexJCWKFzEXgmti++kVb0Wnj/fOxsXrVSOivFcDNKyk5R+fSUzERj1LBYvhjGhdOUsvOX/1wqTSuRh21OHnp8wAG57PWLgEQ4xnG2X2l0CLAq/Kb3U0VR2GzQtpOmKKZ+T0n8HfN7sEb1uXF7AXfxs0HfgwgpLeqVGwJ+so=,iv:DgQrC2WNr+wDbIWoWra8B7qQCeVrFMPi80QTR4EUO5M=,tag:VV1FVIJ4tKy/0ppoL7j0yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
