# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
  namespace: default
type: Opaque
stringData:
  HOMEPAGE_VAR_SYNOLOGY_URL: ENC[AES256_GCM,data:0xOi/eDcyP2qg2Fsx/bIzEltrHSJug==,iv:+SMWZzhNpWY9KbkSzd6OdcCX5rgCH5RUga21kqDM5DQ=,tag:38pL2PuisRShFLauxg2FXA==,type:str]
  HOMEPAGE_VAR_SYNOLOGY_USERNAME: ENC[AES256_GCM,data:OqYj2+B15U56Rfk=,iv:kLgj0FN+OabAoMGVROD3w4xxX6jE4IMYroSL9G1vkNc=,tag:TyOf5qA1SRWt9fXawuHofQ==,type:str]
  HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:6x2QpL0D+HJT3zCUD9bw5yzCNA==,iv:RWKaxssw2oiEJSwB8+WxnfoLho9RKyn2QbLMLb5xrJM=,tag:4sa+cHmv8hLy8d80Qnc/+A==,type:str]
  HOMEPAGE_VAR_SPEEDTEST_URL: ENC[AES256_GCM,data:St7gjiNo01bkDe4xe2EvGPMcYw1ngj/bZOemIMQx14gsyub4xJj+8IMhMtx5u3QO22g=,iv:AvhSxZhq8sES5buLrpCJ14CnU0f1e4JbSi42KWmYkSE=,tag:y3SgxwNpHsxlEYpDk7g08Q==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:7mrw3DRs173K6Er2oJXUCMcJh0GrJw==,iv:gJlGoMe9Ul9OxVI/z+mgXnXgOmhyZYmSuSBufyb1xGc=,tag:diN2XuSeRNh080qOj61OEQ==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:dmRu5BEZIC9xpAoZZkXGcPERki3MxBHzVIeWy0rfZzo=,iv:PhrYHbvV37D2Aihd51MqC8S/Q8naewguS03LiNCcc48=,tag:o/hsPecdglBTdjqu+C3Pxg==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:I6RMn4a3Jk40lGDyreLm9Qj4PwDQmkDJ3SYFi2o+D5E=,iv:DTqtSVE9rfuKie/jU4zy+6Q/HT0dJeICSkZb+y9l25s=,tag:mbExhuwWmk8UBG+nIMMLZA==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:zeo5Zvg=,iv:EScwSkssOUXz2hKcL4SmVy/CX1e7GtIMwIyyarbegzU=,tag:azQIFHs3iu8UJQd8+FhPiA==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:I8HM8Bv7AY37LQ==,iv:H6WQbGLGSSWza88KfCXJK+4psPz4UVRtKCGQh4WtsPE=,tag:2gSNB+dRaoWVcNsfCVtfFQ==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL: ENC[AES256_GCM,data:HUm8sYkC9J8gthp2FmTtIaG1,iv:0oSL7o//JMAS/aCpeABNZHeXMuZjH2Mu1p3bbpCJjn4=,tag:DGeiyYo+sZbN31k1D8jIxA==,type:str]
  HOMEPAGE_VAR_PIHOLE_KEY: ENC[AES256_GCM,data:HutYaICiukEE,iv:oVDy0+BHOIt2ORHtepl5S6tz1rHy4Zko2y0LUKrYqMU=,tag:eJSH7HsKgOsfL4MxbirMig==,type:str]
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:wY21UMugcc4sBXBThJJ7lRNR,iv:Ucc2lfruHpg07db9kG6RD+nNAg7jqzCSmVJVWVKvLQM=,tag:iepOVPyhWSgBrBA7YNdLWQ==,type:str]
  HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:fFAIRg2+icRIT3A=,iv:pQnwI4zueQqQGlzkIwUOU1bNO49RqcMWvmWjyy5hU0c=,tag:4q+UMk0YCHia053mg7F3RA==,type:str]
  HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:lc/gxQgKGbbxTKJEGIZha2Xhwg==,iv:ZZGKTZosCbMDYro7UKQlsfEzRfPIOq955eaTEVigBuQ=,tag:fsH5CWRuDMAsGXtN02uDXA==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSDUrSEdlQ1V0dmd4QURF
        dGpPTzZxanNnajlGaTB2cVBOSWl6VUdHeTJNCjhxa1pwRjZSZTF6OFdsMkd4UjBY
        a0IxQ1ZHdXl0ZEg4L1Q2ZmJON3pheEEKLS0tIDFIc3l0SUNCWlVSL2pZSkVTRllm
        N2hiK3lNVFp6YVhvb2NkbXFjbHZ0bkUKti7HI9QEWmq1WOGbABDuT1O6/DlAiPjO
        alb88A+X1kAgfwmVRnDPuPoOQEYTFaa4X6wBImo4BHgZSgVATjZV9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T14:27:22Z"
  mac: ENC[AES256_GCM,data:YBxu1tum64d5o8x94V5lme4kDAw2NtY3LOb9Bs3v595PVd9g67Xy75v7+BsabocjJA602Vn12Y/AUEYdCM1Pxg7tMmFCG8RyU+DFircFoHgeyPOC3o6KC3db6KqJYiH08e+p87XDwRy5RklKOCeKtB5lnEGnNaYdnUfVCns5Lg0=,iv:LoIdPtwgzC5wJFNKe7FmWbRGJhVuNv+S6t+t8LEvq84=,tag:T6finw+U6gkW5hs66qQ6zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
