# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
  namespace: default
type: Opaque
stringData:
  HOMEPAGE_VAR_SYNOLOGY_URL: ENC[AES256_GCM,data:5REToUlvz57vTCWxMDAwuvfSl0B4vA==,iv:/71SGnKe1F5E//88oMOuDaa1FVsYlx/hePAGIypP1J8=,tag:E9SyflvjKyr1EqdlR2CxUA==,type:str]
  HOMEPAGE_VAR_SYNOLOGY_USERNAME: ENC[AES256_GCM,data:BlyWXvGfzXkC7IY=,iv:cGWToDe8XY+p7DqV7Ji+rDbp924YTNitsxUrAujHowU=,tag:K9AiX1mwkXivPazLjEKtNQ==,type:str]
  HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:p42+EXXVQjVLn8VG0KCf75fgWw==,iv:vhgCUNe5UC2cxNKX+/eQMNwtCCowoN8vNZJq/h5noYE=,tag:cWnRDFuNZ1+oBOk57p0M/g==,type:str]
  HOMEPAGE_VAR_SPEEDTEST_URL: ENC[AES256_GCM,data:1NbhgznmmYtsFxerDIsLlyJd5CTFYkyuHc6ISocWIA1PfZJ7/ic+KWzXk+DRXpKETKk=,iv:eDX1DNhI3vnxMN+RMm8xzDx7bILLvAEmF0+XPs2Efws=,tag:FOg1UF3HRVFJzijzV5LBXw==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:uUemh/2OfR9HSwtT/J6f0b6jvwW3Nw==,iv:7yDhgOjW9gYZkFsVHZuUTtJ7wdK0wDDch0BWHruf1v0=,tag:4iVa64WQ7PI+5HEWhnYmqw==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:G3ZW/QVmv7KLob6hyJUQ2crieeiAe+Zo/hiYYXQtHLM=,iv:b3q9tOXaiMb8PoH+vbS0GU1Qy8hIhDCz42unRULQPnk=,tag:1JBQXG/mRHU8UZtPCj9aSw==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:XfKAmhA/V2qzH5Aa3tAIuKXsSyAjNrqkquYsqDoR494=,iv:EubwoOHblwCvVDHZEgcFHaAs6o5ScryNC0/dJBLurP4=,tag:ecBEHixMP4H0CoJcw5K6VA==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:5NZjf/w=,iv:yQD6zeKT/Z0QR9A3pnQBx9oYxfsWmsIsxpOpaXbl3ts=,tag:xuUR1Lsfg/MxF7xAxZ4dQA==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:5VyWBKFlgt7C,iv:Qjp6vXQ0bIozq2XiBY5eA06PlqLzAZJ7eDGoSQmEouU=,tag:p63L3hNrrszYkBxfqjdfPQ==,type:str]
  HOMEPAGE_VAR_PIHOLE_URL: ENC[AES256_GCM,data:YfoaEd/5BnpsuMLS4mhCwhPB,iv:5Da1EkA0R+of4RQ0cOHKG4kFiZ0Oc5e/VoDCtO0OuIY=,tag:pS93cyI/nTvPIJGmmo4n7Q==,type:str]
  HOMEPAGE_VAR_PIHOLE_KEY: ENC[AES256_GCM,data:+jc4dtf/FJMn,iv:/VfW9aSdqSnNmSwa8rLb32jICsRPPoZGAGIS9MS6mfU=,tag:+tYagBlNvDahPPn6xvTblA==,type:str]
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:Z2RAMpvR0r1tWTrEiLYUsOxB,iv:TOwKaw12R9A8yFaWS4/JgK6ruJN5SKJ2X1n/qQJfBgI=,tag:LVnrXZD3HRxGcXlucDrnrQ==,type:str]
  HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:rPIlQptQrI9uHqU=,iv:44JkKqvJhu4dAEUQX+08mRdut8LvoWxWpGADFLCnqcE=,tag:vSPibR+pBvY2r3J5210Vqw==,type:str]
  HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:cofyKgeRpVmqepwDaYng448ZuA==,iv:+/M3/v20RrnhELUhftUh13xh5kA6MPosYYKdSXjn30s=,tag:9EXOP50VLDC/+a8sIoAPew==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBielMvb01lRTVmUEVWcEk2
        VTVtTWhyOFFlM1hrWURPU2pLekl5YVAxS1NjClNBbjhkL0JGMjg0cVczdlJmTjFQ
        MExFZ21KWG9ROU40aWhVNVFUakRhZWcKLS0tIGNSaU4rSHlmV09xUHFwMlF2Q29Q
        VFQ1LzY1MkFVa3QxSU5uUUhsdDQzTkUKD2JWAEhx/+zLwIWUZaZE5GMiGkQ200sw
        6tntFjnkj+j/RSzRD3nMS/cWwmW0Kpis81aVOV8dkFddx8P0KJjSfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T13:21:39Z"
  mac: ENC[AES256_GCM,data:81ybXs9iLHADNvepybvBIrX+7+2iwERIEgc6IXCTokpsuPgl6zct62/OGveczHxpdTGHOqNasrFsl9sn8KulQV/TW0iwlV+Vpue6X2vzdIIKiPdzoe73GLoLD05Re4Er2yj0BKmxrawYAgNEkv6ZNSM5WqXQ3FtnI/oeDXxe7Ms=,iv:LVrz76itv2Rd4FPtbAmv2HPGUuSGFkz6Bbmwb5cq1Ws=,tag:Zo0uRK5Bo1ogR/H3IuBviA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
