---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: immich-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/immich
        property: DB_PASSWORD
    - secretKey: NFS_SERVER
      remoteRef:
        key: secret/immich
        property: NFS_SERVER
    - secretKey: NFS_PATH_LIBRARY
      remoteRef:
        key: secret/immich
        property: NFS_PATH_LIBRARY
    - secretKey: NFS_PATH_ARCHIVE
      remoteRef:
        key: secret/immich
        property: NFS_PATH_ARCHIVE
