---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./ocirepository-postgres.yaml
  - ./helmrelease-postgres.yaml
  - ./pv-library.yaml
  - ./pvc-library.yaml
  - ./pv-archive.yaml
  - ./pvc-archive.yaml
  - ./httproute.yaml
  - ./helmrelease.yaml
