---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-archive
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - ro
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_PATH_ARCHIVE}
  claimRef:
    name: immich-archive
    namespace: default
