---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
data:
  config.yml: |
    mqtt:
      enabled: true
      host: 10.69.40.4
      port: 1883
      user: "{FRIGATE_MQTT_USER}"
      password: "{FRIGATE_MQTT_PASSWORD}"

    detectors:
      coral:
        type: edgetpu
        device: usb

    cameras:
      carport-front:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_CARPORT_FRONT}"
              roles:
                - detect
                - record
      garden:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_GARDEN}"
              roles:
                - detect
                - record
      left:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_LEFT}"
              roles:
                - detect
                - record
      right:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_RIGHT}"
              roles:
                - detect
                - record
      back:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_BACK}"
              roles:
                - detect
                - record
      foyer:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_FOYER}"
              roles:
                - detect
                - record
      kitchen:
        ffmpeg:
          inputs:
            - path: "{FRIGATE_RTSP_KITCHEN}"
              roles:
                - detect
                - record

    record:
      enabled: true

    snapshots:
      enabled: true
      retain:
        default: 14
