---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
data:
  config.yml: |
    mqtt:
      enabled: true
      host: 10.69.40.4
      port: 1883
      user: "{FRIGATE_MQTT_USER}"
      password: "{FRIGATE_MQTT_PASSWORD}"

    detectors:
      coral:
        type: edgetpu
        device: usb

    cameras:
      carport-front:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record
      garden:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record
      left:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record
      right:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record
      back:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record
      foyer:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/stream1
              roles:
                - detect
                - record
      kitchen:
        ffmpeg:
          inputs:
            - path: rtsp://REDACTED_USER:{FRIGATE_RTSP_PASSWORD}@REDACTED_CAM:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - record

    record:
      enabled: true

    snapshots:
      enabled: true
      retain:
        default: 14
