---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
data:
  config.yml: |
    mqtt:
      enabled: true
      host: 10.69.40.4
      port: 1883
      user: "{FRIGATE_MQTT_USER}"
      password: "{FRIGATE_MQTT_PASSWORD}"

    detectors:
      coral:
        type: edgetpu
        device: usb

    go2rtc:
      streams:
        carport-front:
          - "{FRIGATE_RTSP_CARPORT_FRONT}"
        garden:
          - "{FRIGATE_RTSP_GARDEN}"
        left:
          - "{FRIGATE_RTSP_LEFT}"
        right:
          - "{FRIGATE_RTSP_RIGHT}"
        back:
          - "{FRIGATE_RTSP_BACK}"
        foyer:
          - "{FRIGATE_RTSP_FOYER}"
        kitchen:
          - "{FRIGATE_RTSP_KITCHEN}"

    cameras:
      carport-front:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/carport-front
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
      garden:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/garden
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
      left:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/left
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
      right:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/right
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
      back:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/back
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
      foyer:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/foyer
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
      kitchen:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/kitchen
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5

    record:
      enabled: true

    snapshots:
      enabled: true
      retain:
        default: 14
