---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: frigate-secret
  data:
    - secretKey: FRIGATE_MQTT_USER
      remoteRef:
        key: secret/frigate
        property: FRIGATE_MQTT_USER
    - secretKey: FRIGATE_MQTT_PASSWORD
      remoteRef:
        key: secret/frigate
        property: FRIGATE_MQTT_PASSWORD
    - secretKey: FRIGATE_RTSP_CARPORT_FRONT
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_CARPORT_FRONT
    - secretKey: FRIGATE_RTSP_GARDEN
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_GARDEN
    - secretKey: FRIGATE_RTSP_LEFT
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_LEFT
    - secretKey: FRIGATE_RTSP_RIGHT
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_RIGHT
    - secretKey: FRIGATE_RTSP_BACK
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_BACK
    - secretKey: FRIGATE_RTSP_FOYER
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_FOYER
    - secretKey: FRIGATE_RTSP_KITCHEN
      remoteRef:
        key: secret/frigate
        property: FRIGATE_RTSP_KITCHEN
