# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: frigate-secret
type: Opaque
stringData:
  FRIGATE_MQTT_USER: ENC[AES256_GCM,data:CI+y3nIAU+cF,iv:z5TlTU/x5ESbNQa6NhmSKR+x9lFWZ7HMseapOsql8i8=,tag:SHKmA0GB05PN1qQAM4S2WA==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:9Qn73ONHYWM=,iv:9kOGALOkP4yWMTPRwke6DaxZDDK+CJiskIDDzsNY5hQ=,tag:AwkpY2YyGS59iESxg0QpBw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVUYxS1dTVWF2dFhyVFRV
        a3ZVQytJdDBJMjRjY0tKcVczZ0UwcGROWVFFCmx2MjYzaHZlTFRlVkRGdFg3QmJy
        NTU3N0E5SUFzR3Z6dWh6bmhkNWh5V3MKLS0tIHhTR1RlbXRqM1VoSDBOclkyLzU1
        YzF4OUpKL2NhZm5NWEllWHl0UlVDQzgKpB7CZBdyhWWLOKnb1u7IPYONNdE5nVtl
        J4mAjAEIR0nJ3mD2U3wRQICsbWHBf3atZ/8DdQ6WdFQiy0QFc34qKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T13:50:05Z"
  mac: ENC[AES256_GCM,data:lSvOom/XI1VBcDEgAMPAhThc+Au/+lAVnheiiw8BkskgWuBiDRMLfhCeTnBKfsGG5BqT3R/d1OsY0TgVTH1fVdYz/KPjAMagYpJ0/FaQVEbadhKbgCFHZqhxPJ6T2bg3xWfJvjTJXb4kPpUFsfO+nEu14qrfJVtjF5aS2HZebFE=,iv:pK/qCDFaGEQ94f7xqu4gHhQx1Gwj4IQS3wmynXPJGtw=,tag:t8EblCeN0TCZAGdH4FXWvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
