# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: frigate-secret
type: Opaque
stringData:
  FRIGATE_MQTT_USER: ENC[AES256_GCM,data:0k2GttpZMfyU,iv:oJzUvwLIIR2wbrwCIfapOJ3WQ8fd9zWPLyIEwoWHoRE=,tag:VJ/Fksg/+wa/dt1M21UYyQ==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:W1wyVkqyudo=,iv:eOQp7zFndknQCHyFwFA6Y/kxmzFr7aEPg8n0JMK9jtI=,tag:C4ZdLXsYn9VT2jwgjRkmww==,type:str]
  FRIGATE_RTSP_CARPORT_FRONT: ENC[AES256_GCM,data:CjFsMEggg0HslLwMwQUFaSYuFdzB3ciWX0ivzQVbfi0oxDUhlpY8H0rRQTLORzaMkl4yby6KlNYzKb/z83PPuP/xyHn7Um+z4tbfD+cNojSnvE/ZkfvoWzA/p8QSj8dPnOC5hIs3McmCNBC68p4x/6JF1WYZ1IVYBbor23TZ5gv1GL2n,iv:o8oQFIrzYbSEp1LPMPMPR/uGHSpYhlveVuBuqqNDEAs=,tag:7Jtes7sNAnNGAx+i4z0PWg==,type:str]
  FRIGATE_RTSP_GARDEN: ENC[AES256_GCM,data:e5r8xPm/Xqdi94ODvotvplJgWtPohMILlybbRxfud4s0N6ojgOKTLV7kv9HuzutQleMQ1tDqUkLnzIfYORbeSXMmULVwxIwWd9Ex4dlvazSzkURvBH13l+6ddROUW/kPiHgzL5CL1LLd3++VDQCjemVv9iY1R//1ulQ0P8Dm0+JnQtBK,iv:dEHXSvqHZZ7jbRAgIS5XnDKWRPvMWV80Bz65DrrQFtw=,tag:RhqCTMLjxWxf3SZRl2Ag1w==,type:str]
  FRIGATE_RTSP_LEFT: ENC[AES256_GCM,data:K8VT+ECUDeAaup32RhD2YOORfEP6KNA1WH27pDqD4JxKRVevdbYXYYMe1p78GeEm6YzLJQMeVvoDgrmvYGRshPmv3AvojSnFChsziHsju3077n5gTJcjgVKaYI3GOgZriwP4MK0nqsR9iYTeMMxq3uqapiy5NIc5LwjIhO4DoWv2jkDE,iv:ZUCC+Cwh5HZzEu5GrZGSN2sMX6rLivjDCEFrW7ROhT0=,tag:6fvE3BMTFkOg/4ZoWVMFJw==,type:str]
  FRIGATE_RTSP_RIGHT: ENC[AES256_GCM,data:w835fSlgyWLxAh6KEHI5bxew3ef0f4sBuqyI1/UpIa/7KTFK6VMabyljZVNmKwIMILxrcAyM9j+MEklZ+lnasYSOw5iOwIU7bEDyxu/qe8RoAHFJ2eqxxamK4/U9ZS0Q3BYD8KFpwjNEFV8yVy3ZnGSxP0iyMyR5qVjGrDjAV37w9/sd,iv:1YtZE4Scrxnx9aVA6WXlSDXFDd2vk4JzjBpzQ1pJD7I=,tag:Upf8RQy/1BiN8rcQqzOYBA==,type:str]
  FRIGATE_RTSP_BACK: ENC[AES256_GCM,data:nJKsT4JGX3RHi6aXWn6b78I2EBiFti98OpCmyDnOdNc7YAj1ylf6/ZcOG/cNVVHZzGTV+SwvBiFtnHZsnayBYVUzfbZa35N3n9ch6ADe1HgZ61BGFaLYSfZfLU9R4Q7CAyG1FY7pzzOmyS+nK50l5EWVhaJWC/7iC7TT0e1J8PmnDyaB,iv:N1x+x/UUPgWDnVzDQOC2FW0cdcd6xRFfVv45LCUrsA8=,tag:h8npvwnTFVhKSG97iggevg==,type:str]
  FRIGATE_RTSP_FOYER: ENC[AES256_GCM,data:WCsfrw8SamttKeHfWblZcUvidmd8jIF1KwK1iCHbG8wXxgQDx0yXYalknCiAs1Krv16CzHAtekDCKLE8jG9NRdMWsHoHWxjFdV4jv+w=,iv:1ZXz/A9ZOqSj5PpvB+OW1Ecne6ERM82cYfBYUKONzvw=,tag:r0NV0+B8znL03w/i903YfA==,type:str]
  FRIGATE_RTSP_KITCHEN: ENC[AES256_GCM,data:mstUToT5HLbrlmQso/77hZUylwxzxes2sU1TVy7JnlgtjxVusYBs2tADEcOt0AZU9nVOztYfsU7SWefznCzq7459jK4gsXwYsAu0lwh+8N4yezKrChtiHb2KmTfkvP0V0kT9KQ1CSyaPd2maP4FZiKzR7WDluFBaoJL8JmIP/Ke8hrEK,iv:ANKih33LYyDX1F1qlk4pWKH6pq2iOdH/0am4nzV9nZ4=,tag:h2bnsbxng/4nk7971PqFuA==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWEdTTG9JUGFTRi91c1Nu
        Q2c3VVNNcWNuNE1WK1lHU0lTa3RVTVUyWFZRCkgvTzdmV2tZL0pXSXVIUHBISDlP
        b1JPZ3htL3BuMzZ0enAwSmx4cXBNdWcKLS0tIE9MTEMvZ2VDeFd6NWhDU05CUkh5
        Ym1WWDVFRkhVL1dhWHpTL2ZYSXFEdkkK/1fwno5L1j7sNQz6RkjJsL8BdImUF+CJ
        SWkYq8Oo1mOmVL5VNlMkNe1qhv86vW17+4pibHlMN1dQtrWk+dUHBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:31:46Z"
  mac: ENC[AES256_GCM,data:QIjSFnAKus7TK7xzt9hCvni4jF+qfxPWtLki8/aJQ8z8VVpYuUEsiAjRijqH9feSpvCHU6Bkei2YtPn308ci9Umuq/trwt0fmjqgCiNUbqpPSG45XMiN3L6PqzsF74VSFagRYGhMZcK8lhPPPK/iis7HJuUN7VU9p6pUfoWiNlw=,iv:/k5VfgaKkiDzMNItkJZ2SBshXlyy2VU4Hu7yHGG1ufQ=,tag:GSSFEFvEKbK5t+Dz3fjdkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
