apiVersion: v1
kind: Secret
metadata:
  name: frigate-secret
stringData:
  FRIGATE_MQTT_USER: ENC[AES256_GCM,data:mb0SuaMmFppu,iv:mUCvAKducKv4Z3j2y0eFy4OIlkzIEecqJxvQ+/1xMfA=,tag:TTKZtn9u+YnvM6Kz4R6rtQ==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:sCOuo91v0Pc=,iv:JJM4Bium0r5dWyOMAJXTmwHk4bo5HJutzLOd4xs+TDU=,tag:qTUUc/Q3V+Y+Ajz5Cbg1Dw==,type:str]
  FRIGATE_RTSP_CARPORT_FRONT: ENC[AES256_GCM,data:0M4j7KHFsW6Opp5Ul1eby75gcPNf9vXsWGyYkZBGVYu6/Z6q9FkRDp5fQgqOu3DcSsizwlH8kNXUoR6nV0PoCLAoQ/3W6xcncbRmbFGz1Kq5o1xisifI28B8kY7huPk8oibL1ljxhw7hOgZejJc=,iv:pKCUUtqZCNEHtTUSrrdMGd+gnB1ta+L8JzwShAJtQhg=,tag:OjOADeFCLeKYsug6XBXd4A==,type:str]
  FRIGATE_RTSP_GARDEN: ENC[AES256_GCM,data:vkasrdL+5IVKFSeFx1kQz1drM7UjxKGdDvOky/J35Ke97ZoT6723wBtDPPODOWm9IK40b/pA/XdBwTRZ6rE48w1PDNYyKLpGZEM31eOWew6N/3+HUJULZF7OH+Xj97Uc/vbo6EbygcKdfdU9VzM=,iv:ROQR8OXz49Ifk6dH0iXhmbISRAE5VbEgDfD/bIwzg90=,tag:9UdKOPqs4VDhGRYqkhd7Sg==,type:str]
  FRIGATE_RTSP_LEFT: ENC[AES256_GCM,data:GBZsrRa94QcvjNkUWJBBeDk7uRBoAtpRU5TTr5Ow5viImcXDWwihR+W94gMfCKuBDZU8ha1bDw8vNggv8A63cULWDcw5BB352OAilPCnDbd+CeJ3cuUCXb/OlIqXre2pgB02EVfSGBC9EetWt3s=,iv:O9EsQHS3Puugu/HGsIICX8hH+Cfs8VAJ/OsSuSdAvvo=,tag:VICIbvVwnXBqeyNOky4z8A==,type:str]
  FRIGATE_RTSP_RIGHT: ENC[AES256_GCM,data:yVWF38/fhwOVkd6Paik67GFnaZfSQTBp5uUYBGDOlZ3pj3htC9PaWXYfA/BFsW2rQ/clXfELqTcND2rVV1wEdTnqmA9mzORdnnsLHhWZ9Leb1kI86qC+YriOtFFuXXWHFlxY2kgizWxHBLtkALo=,iv:5XbFgfYn1zeBOooJ1EhvseQDWUK4p2543WR2s5kTZvc=,tag:OtMrlRFFHZjcJqoQgOJRHQ==,type:str]
  FRIGATE_RTSP_BACK: ENC[AES256_GCM,data:TE8XVTPj6xm26AsoMxjY9AYRcS3HAn7pb7459CTYvEa7LicaB4PgYMpYp5x+q1Xtg9hKmzExf071C7wT5zMeuyGG3w41SKzlDGA0M2KhjfU4Z5mMsJVb48lU+gKg8JJi/2VY2hVr0R2O397Oi4o=,iv:QeY2G9rynzqXUikLbEb2P5SxOL1ip9ZPAjCOy7INHME=,tag:/th4kytZlgOr3Y2t/zzbWg==,type:str]
  FRIGATE_RTSP_FOYER: ENC[AES256_GCM,data:3sSJilKFb0IYDNCLpKSBtRlwdorCAsYSEf6bm+txw+qqCixHZ8zAreIcRsF9ydseE3k7wEHx1g==,iv:cvjdAT70LRTtO4NpGRi8Do7niTrjhsljM95DuwtTsUI=,tag:n1iXUzIarp6daUG73L3y3g==,type:str]
  FRIGATE_RTSP_KITCHEN: ENC[AES256_GCM,data:zkNO1ovAzkHN9fmGmJiv1UxxZjSMzlyotjQBx8KH+Og+rgxw9zUvuggReNVQmS5OWNjNrAIXFgoJVbqLwa2S4Ke3nwNWJCCJjwNUfN7TS1LjceO3KfMHE6L64HeJbfJFaNbQF7SHZfhfQgc0Ypg=,iv:ssVa8cs0leRN/7UtpCQIIIe4KurJRG4+JbS/PQ7/BpM=,tag:fbwxrGgcF2a7LgH0vCKdzQ==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Zm9PVklsU0l4cy84cWVo
        VlEySGE3TlQyOXZER1NaOW9HMmYxOE4xWFdZCkcyaDNuREszWjBrK3ppU0pHNnhW
        aVExL1FoeGp4dEZwczNVVWt3dDhWS0kKLS0tIDE4UDlYNGVOSDlaUDhjTnNxYzEx
        V3VKa2grblZ1QTFzaUJ4VVkrTGFNUE0KEAgX0SQvI0ua7MKThyrdDeL+vfyoRDmE
        xMGeYgkJg7LzAJf/zOeNC3Fcq26kZ2Xzf/xteLVlIntsTUf4kKjHWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T12:38:26Z"
  mac: ENC[AES256_GCM,data:CGrBt/CNuonhD/arfErZv1cf50Wct5jmSXQbjI//Ib1LsUnqD/W3EuAGd4APDR9bOcE7kjt5DE9Kcch2fpvYM4VCEwlkurlKASs8yNK+UpYl46xDMoOF4BZTV5SlV1JwRQ/XOmaMkmQKGi1/er7+n9bZ8OE4Fb21MJoYlNc2eNA=,iv:3ETNeGKQpGpSU8zSm8sDo46IgPdyTh1P4sK2hXB8Pcs=,tag:6pyFOOmdXYb8/rmkZfDZxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
