---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-backend-ca
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFVzCCAz+gAwIBAgIUFbPbi3vPaQje04mEnIyelSTyJMMwDQYJKoZIhvcNAQEL
    BQAwOzEiMCAGA1UEAwwZSG9tZSBBc3Npc3RhbnQgQmFja2VuZCBDQTEVMBMGA1UE
    CgwMbWluZy1ob21lbGFiMB4XDTI2MDMxOTEyNTAxNloXDTM2MDMxNjEyNTAxNlow
    OzEiMCAGA1UEAwwZSG9tZSBBc3Npc3RhbnQgQmFja2VuZCBDQTEVMBMGA1UECgwM
    bWluZy1ob21lbGFiMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxE6P
    v2Z7bBFqQ5gjpog9cs+DPh+Fi3ZGn4sJchjViWPa1dzQeFMqiVpUVTyDYK4Ih4iF
    RKZ8nyYG4eFp2A9gI/dcgmlDxzuJZ1nV4LGmnkMPu4qnAf6DZfmyOPITj5uBis0j
    dnmQzfl8usa4VTeqkknKbDSpfqXcvtSgT24G3syNf9LsyeL18mUjCCjsSrnO68SQ
    FEMEdrybR9BwLzaW5KXc3hJRl+8r76xrLo2g72Y98uTphyEkAKO/RJ7CFXn01/Xj
    SBtnq2tHhHvmUNNE5yQUhymbWme2cQGvjO1NPDUFANTfG1GxWggATisJ6FJi+WRi
    oAmZdGvgwpP6J4Xd48COcYTuRwzfh1qwq3S413fLHAzjRsIU5bdgaLYY3FhL4VwT
    Cc+lsAX/SANRn9idYY9/C9GcKCd2o4/NiV7ifmCJhHdBTMopqS+tzUwnAAkKVtLB
    kUpdd1mAXjZ/TcNvdNkfnyQxHEUTNZi11V22gi22RNh7G3B+QtDyUTwm/N6mOLxC
    pG9pykfdXKa3XVjtINVQhK3wG9lqKW8Gnl0JRUqx/CGDMppmfILFYkHsKC5Ttydk
    +8sMPwzjL2MbPzLcrHr+dDQIGOVWqs4RXo39xOxTGSy4nZQUdJLHxuH+Be+P1kZN
    3wWz3JM9uhdgMFwwPS2Ru/JwYM/+RZiGoTMpBA8CAwEAAaNTMFEwHQYDVR0OBBYE
    FD/3ADpuUz4SYhy7oTGHunHE4295MB8GA1UdIwQYMBaAFD/3ADpuUz4SYhy7oTGH
    unHE4295MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAEU7dvF7
    qmmRnEKp1Q8aY4t4E6QQ7HL4c2/HEyg3EOmzwzo6kv0+6bOKPcknC4kiIS+XtoCF
    iEO+8QNRArgR6VVKhZsmZAGAojcIpwk8GW9E+ATvbndjxtnNDjjoUjTiKv3YPjAO
    DLYWeNtwgl/CGdAdHwRk4OV7IWPKply78owduhWkkNXpZQXpoHwURzjYtpNlB5En
    iaxrQSoB0cHLVUwXqeG32d+xLHq+uD9S9gpFsFXC5E7VXke3oYwSE/NyeZmRvFBs
    tl2BpL2k+zsWNnao9plEYidYRMCGP15q7i+1Cw72Xq+D4NVWdB09Y/06qfVW+paF
    +Pz8yyZWKLz1Ak6Mb1tdlPQNpJ4HDfIjbplMlYQ84WNTqJdlgOIm04yXIgUR8OMK
    IWcd0J8jzRZmH1DYOvtf8jw0SOTzqtVHgYabT2WNW+9TXPBiQWzd6HZqDeGksh91
    WA2KpHhVTmxnxcEq/IugrCKgYhLbuXcbaSW3CFT1ThnivHDRlWk1U2ByrlKnKQ/p
    Q0R3LARVDQi8g19Fqu2ck+01kKvK0qlBWMipRKUTTOYGfCK2192xlvF0U5mMN3ud
    EgHkfIy11+SWxkKUY2T1wfMTirEHbeBui+D/ZtND7dpm/T9/lWPKgJclVNNUx5ua
    WVJfIDl5I2gz20m7MweIDVPep94a3SFIlRb6
    -----END CERTIFICATE-----
