# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: decluttarr-secret
  namespace: default
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:hhMwTjJ4aO7W5NQ2saFt/arWx90wrvhqo/T2NzKxsQ9+MzbuRvdvAgQ3XBAB8xKBv3AjZw+o/1lH4Fn+P9N2lcxcj8XdCTaL5dSNrp++apf6X49AkJ8V4sphWQ+THbYRlI6dZoLDIsX8zeRyFtgo1EBNZzuvSd2ABRmnz5zMuIYBi5eBlLzj4+ZOBowc1seaqJ55viisszJWmJWYav78/JPJyBT4eubGu5ByW5Albxep6vf3Q2y1btsvCK1vylNF2BhTl6vdVljes0Nqfp9GRK79ZYxQ6MSIgVdwZv7Y46BXJmUrv4xxvHAXAraDUNhmLmsXL8MtPVtdvdm9OcxRUWf/z10oj6v4VO4ENcJOctebl4Lt1j2cUidcYHV1Y6FyKDthxW0rSmj6GCtNWejpmkToIe+6gMmkuK6FW3uKKM9+n4ucPuh6JMABG3QZBQzYlspOCDIJvWIssF/sIbhsDf2FEjVTxpWkWLIQAv16e8hRHb1WRuC70KBN0r1lO56Qr89pIljEfWUitlSqVocGcIvh8xT59nE/sT6OPeZU23g6gCJ9/LxqkFIQ7zvug2nf7hntShK7i70pc/FXSiC7wI3tzkis+Pnwe0yMz5+Sj546fScAgIAoVQJWKhz0b8DeTuG6Ou7Tc1ujW6oYItMzP8mAyM5Uouf9XoEz/7g0Kw4/Mj11HMVOMMJqa2+P/W/rMBw28RdPq7wkYKO4IcaWAuxai5HZDLu1KCZsUdHtCX3ZaifpMf+TpeGz+yH6tnLaoEbCTcefWJBt3UWfRzWwtKOewiPRBFj0BWmm0RhV85o/0FvCrJ8yG7mmySJtDa0=,iv:6mrbbJ3AxJtgJJZSUTdAHdvyHm6cjiwpUKy1G/DlMJw=,tag:bOJrDAtM+jgP1235nodaaw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU21kbk5RRjF6cHVESGRw
        R1p2VnN6NmRaUjNYeXg5S29qUm5oUkpYRnlFCmtIeHhRdDd4YTlob2RPV0JMTzNL
        WmQ5WUVwdU4wSzV3L1BhWnNldHB4L0EKLS0tIFdqeFNZcU4ycFVyVmJVZEhNYUVF
        bU00TUwxbVRQK2Vza1dvbmMzUnQ5bGMKUkv2v9Pa6HKBspDGgv7hkZLchCNomc48
        j7eNNM3MK/audWl4CF0QsHE6UrtpCZavobOgJqGrobtygvSrivjhiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T13:38:42Z"
  mac: ENC[AES256_GCM,data:2asqb7Dmik1T/Bw0zZyrjS6nUSTqlYy3i7lWaNwcYzAYB4C06vyrt14UBGjw14CgNpkTlYpIIDURm+SZz86NSxrJUYsyXRIWawb109wOSNqNI5KXp7z7qgjWkUbc2XF/rANv93SpCVR3rRXINM/H1j/2G9PP0eSxfTAuXKp0G0c=,iv:giGNw4l2AW478Y82xj5y3tO8x2CdYybQj4rAXOPswZ0=,tag:DKeDjWHZ209qEgAytWwnxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
